### Task 2

In [1]:
import numpy as np
import re

In [2]:
sample_listofreview=['Food was damn good!:)','good food. recommended','YOU PEOPLE ARE THE BEST!!!','It tasted very bad..... too bad service as well']
print(sample_listofreview)

['Food was damn good!:)', 'good food. recommended', 'YOU PEOPLE ARE THE BEST!!!', 'It tasted very bad..... too bad service as well']


In [3]:
sample=sample_listofreview[2]
sample=re.sub('[!@#$%.^&*()_+}{":?><"}]','',sample)
print(sample)
sample=sample.lower()
print('\n')
print(sample)

YOU PEOPLE ARE THE BEST


you people are the best


#### Preprocessing the data

In [4]:
processed_reviews=[]
for review in sample_listofreview:
    for words in review:
        review=re.sub('[!@#$%^&*.()_+}{":?><"}]','',review)
        review=review.lower()
    processed_reviews.append(review)
    
print(processed_reviews)

['food was damn good', 'good food recommended', 'you people are the best', 'it tasted very bad too bad service as well']


#### Collecting the uniques words

In [5]:
unique_words=[]
for review in processed_reviews:
    for word in review.split():
        if word not in unique_words:
            unique_words.append(word)

print('list of unique words',unique_words)

list of unique words ['food', 'was', 'damn', 'good', 'recommended', 'you', 'people', 'are', 'the', 'best', 'it', 'tasted', 'very', 'bad', 'too', 'service', 'as', 'well']


In [8]:
feature_matrix=np.zeros((len(processed_reviews),len(unique_words)))
for n,review in enumerate(processed_reviews):
    for word in review.split():
        feature_matrix[n][unique_words.index(word)]=review.count(word)
        
feature_matrix

array([[1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 2., 1., 1.,
        2., 1.]])

#### Assignment task
<pre>
Download data from <a href='https://tinyurl.com/47rx5cce'>link</a>

1. process the data 
1a. remove special characters
1b. remove non english words
1c. remove numerical values
1d. all words in lower case
1e. remove punctuation
1f. Featurize using Bag of Words technique

2. Fit the Naive Bayes Classifier
3. Report the Accuracy
4. Compare the Results from other Variants of NB Models 
5. Write your own observations

</pre>


In [10]:
import pandas as pd
import numpy as np
import re

df = pd.read_csv("/home/shravan/Desktop/Tweets.csv")

In [11]:
df

tweet_id airline_sentiment  \
0      5.703060e+17           neutral   
1      5.703010e+17          positive   
2      5.703010e+17           neutral   
3      5.703010e+17          negative   
4      5.703010e+17          negative   
...             ...               ...   
14635  5.695880e+17          positive   
14636  5.695870e+17          negative   
14637  5.695870e+17           neutral   
14638  5.695870e+17          negative   
14639  5.695870e+17           neutral   

                                                    text     tweet_created  
0                    @VirginAmerica What @dhepburn said.  24-02-2015 11:35  
1      @VirginAmerica plus you've added commercials t...  24-02-2015 11:15  
2      @VirginAmerica I didn't today... Must mean I n...  24-02-2015 11:15  
3      @VirginAmerica it's really aggressive to blast...  24-02-2015 11:15  
4      @VirginAmerica and it's a really big bad thing...  24-02-2015 11:14  
...                                                  ...               ...  
14635  @AmericanAir thank you we got on a different f...  22-02-2015 12:01  
14636  @AmericanAir leaving over 20 minutes Late Flig...  22-02-2015 11:59  
14637  @AmericanAir Please bring American Airlines to...  22-02-2015 11:59  
14638  @AmericanAir you have my money, you change my ...  22-02-2015 11:59  
14639  @AmericanAir we have 8 ppl so we need 2 know h...  22-02-2015 11:58  

[14640 rows x 4 columns]

In [12]:
df["text"]

0                      @VirginAmerica What @dhepburn said.
1        @VirginAmerica plus you've added commercials t...
2        @VirginAmerica I didn't today... Must mean I n...
3        @VirginAmerica it's really aggressive to blast...
4        @VirginAmerica and it's a really big bad thing...
                               ...                        
14635    @AmericanAir thank you we got on a different f...
14636    @AmericanAir leaving over 20 minutes Late Flig...
14637    @AmericanAir Please bring American Airlines to...
14638    @AmericanAir you have my money, you change my ...
14639    @AmericanAir we have 8 ppl so we need 2 know h...
Name: text, Length: 14640, dtype: object

In [13]:
for i in range(len(df)):
    sample= df["text"][i]
    sample=re.sub('[!@#$%.^&*()_+}{":?><"}]','',sample)
    #print(sample)
    sample=sample.lower()
    df["text"][i] = sample

df

/home/shravan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


tweet_id airline_sentiment  \
0      5.703060e+17           neutral   
1      5.703010e+17          positive   
2      5.703010e+17           neutral   
3      5.703010e+17          negative   
4      5.703010e+17          negative   
...             ...               ...   
14635  5.695880e+17          positive   
14636  5.695870e+17          negative   
14637  5.695870e+17           neutral   
14638  5.695870e+17          negative   
14639  5.695870e+17           neutral   

                                                    text     tweet_created  
0                       virginamerica what dhepburn said  24-02-2015 11:35  
1      virginamerica plus you've added commercials to...  24-02-2015 11:15  
2      virginamerica i didn't today must mean i need ...  24-02-2015 11:15  
3      virginamerica it's really aggressive to blast ...  24-02-2015 11:15  
4      virginamerica and it's a really big bad thing ...  24-02-2015 11:14  
...                                                  ...               ...  
14635  americanair thank you we got on a different fl...  22-02-2015 12:01  
14636  americanair leaving over 20 minutes late fligh...  22-02-2015 11:59  
14637  americanair please bring american airlines to ...  22-02-2015 11:59  
14638  americanair you have my money, you change my f...  22-02-2015 11:59  
14639  americanair we have 8 ppl so we need 2 know ho...  22-02-2015 11:58  

[14640 rows x 4 columns]

In [14]:

for i in range(len(df)):
    res = list(filter(lambda ele: re.search("[a-zA-Z\s]+", ele) is not None, df["text"][i]))
    #df["text"][i] = list_to_str(res)
    df["text"][i] = ''.join([str(elem) for elem in res])

/home/shravan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [15]:
df

tweet_id airline_sentiment  \
0      5.703060e+17           neutral   
1      5.703010e+17          positive   
2      5.703010e+17           neutral   
3      5.703010e+17          negative   
4      5.703010e+17          negative   
...             ...               ...   
14635  5.695880e+17          positive   
14636  5.695870e+17          negative   
14637  5.695870e+17           neutral   
14638  5.695870e+17          negative   
14639  5.695870e+17           neutral   

                                                    text     tweet_created  
0                       virginamerica what dhepburn said  24-02-2015 11:35  
1      virginamerica plus youve added commercials to ...  24-02-2015 11:15  
2      virginamerica i didnt today must mean i need t...  24-02-2015 11:15  
3      virginamerica its really aggressive to blast o...  24-02-2015 11:15  
4      virginamerica and its a really big bad thing a...  24-02-2015 11:14  
...                                                  ...               ...  
14635  americanair thank you we got on a different fl...  22-02-2015 12:01  
14636  americanair leaving over  minutes late flight ...  22-02-2015 11:59  
14637  americanair please bring american airlines to ...  22-02-2015 11:59  
14638  americanair you have my money you change my fl...  22-02-2015 11:59  
14639  americanair we have  ppl so we need  know how ...  22-02-2015 11:58  

[14640 rows x 4 columns]

In [16]:
unique_words=[]
for i in range(len(df)):
    for word in df["text"][i].split():
        if word not in unique_words:
            unique_words.append(word)

print('list of unique words',unique_words)

list of unique words ['virginamerica', 'what', 'dhepburn', 'said', 'plus', 'youve', 'added', 'commercials', 'to', 'the', 'experience', 'tacky', 'i', 'didnt', 'today', 'must', 'mean', 'need', 'take', 'another', 'trip', 'its', 'really', 'aggressive', 'blast', 'obnoxious', 'entertainment', 'in', 'your', 'guests', 'faces', 'amp', 'they', 'have', 'little', 'recourse', 'and', 'a', 'big', 'bad', 'thing', 'about', 'it', 'seriously', 'would', 'pay', 'flight', 'for', 'seats', 'that', 'this', 'playing', 'only', 'flying', 'va', 'yes', 'nearly', 'every', 'time', 'fly', 'vx', 'ear', 'worm', 'wont', 'go', 'away', 'missed', 'prime', 'opportunity', 'men', 'without', 'hats', 'parody', 'there', 'httpstcomwpggrezp', 'well', 'didntbut', 'now', 'do', 'd', 'was', 'amazing', 'arrived', 'an', 'hour', 'early', 'youre', 'too', 'good', 'me', 'did', 'you', 'know', 'suicide', 'is', 'second', 'leading', 'cause', 'of', 'death', 'among', 'teens', 'lt', 'pretty', 'graphics', 'so', 'much', 'better', 'than', 'minimal', '

In [17]:
feature_matrix=np.zeros((len(df["text"]),len(unique_words)))
for n,review in enumerate(df["text"]):
    for word in review.split():
        feature_matrix[n][unique_words.index(word)]=review.count(word)
        
max(feature_matrix[0])

array([1., 1., 1., ..., 0., 0., 0.])

In [18]:
feature_matrix.shape

(14640, 14562)

In [28]:
from sklearn.naive_bayes import GaussianNB

In [39]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(feature_matrix, df["airline_sentiment"], test_size=0.30, stratify=df["airline_sentiment"])

In [40]:
model  = GaussianNB()

In [41]:
model.fit(X_train,y_train)

GaussianNB()

In [42]:
model.score(X_test, y_test)

0.5022768670309654

In [53]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score

In [54]:
pred = model.predict(X_test)
accNB = accuracy_score(y_test, pred)
y_pred_prob = model.predict_proba(X_test)

print("Confusion matrix")
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))


Confusion matrix
[[1453  540  760]
 [ 201  299  430]
 [ 151  104  454]]
              precision    recall  f1-score   support

    negative       0.80      0.53      0.64      2753
     neutral       0.32      0.32      0.32       930
    positive       0.28      0.64      0.39       709

    accuracy                           0.50      4392
   macro avg       0.47      0.50      0.45      4392
weighted avg       0.62      0.50      0.53      4392



In [55]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB

In [57]:
BNB = BernoulliNB()
MNB = MultinomialNB()

In [58]:
BNB.fit(X_train,y_train)
BNB.score(X_test, y_test)
pred = BNB.predict(X_test)
accNB = accuracy_score(y_test, pred)
y_pred_prob = BNB.predict_proba(X_test)

print("Confusion matrix")
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))


Confusion matrix
[[2628  103   22]
 [ 466  407   57]
 [ 308   84  317]]
              precision    recall  f1-score   support

    negative       0.77      0.95      0.85      2753
     neutral       0.69      0.44      0.53       930
    positive       0.80      0.45      0.57       709

    accuracy                           0.76      4392
   macro avg       0.75      0.61      0.65      4392
weighted avg       0.76      0.76      0.74      4392



In [60]:
MNB.fit(X_train,y_train)
MNB.score(X_test, y_test)
pred = MNB.predict(X_test)
acMNB = accuracy_score(y_test, pred)
y_pred_prob = MNB.predict_proba(X_test)

print("Confusion matrix")
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

Confusion matrix
[[2619   90   44]
 [ 477  357   96]
 [ 278   66  365]]
              precision    recall  f1-score   support

    negative       0.78      0.95      0.85      2753
     neutral       0.70      0.38      0.49       930
    positive       0.72      0.51      0.60       709

    accuracy                           0.76      4392
   macro avg       0.73      0.62      0.65      4392
weighted avg       0.75      0.76      0.74      4392

